# CASCADE_HINT: Minimal Netlify config for static Astro + Edge redirect
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # CASCADE: Public GA4 measurement ID passed at build time
  PUBLIC_GA_ID = "G-57N05H2588"

[[plugins]]
  package = "./plugins/broadcast-new-posts"

[[edge_functions]]
  function = "locale-redirect"
  path = "/"
